# -*- coding: utf-8 -*-
"""Project PCD - Arini

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HrHfctLxbkpKf_6UwqvoF4KtA3yoPOy
"""

#HISTOGRAM
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

img = cv.imread('mn10.png')
plt.hist(img.ravel(),bins = 256, range = [0, 256])

#GREYSCALE
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

img = cv.imread('ma.png')
img_grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

plt.figure(figsize=(20, 20))
plt.subplot(1,2,1)
plt.imshow(img,cmap="gray")
plt.subplot(1,2,2)
plt.imshow(img_grey,cmap="gray")
plt.show()

#Gamma

import cv2 
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("ma grey.png",0)

gamma = 2.5
img_power = img**gamma

plt.figure(figsize=(20, 20))
plt.subplot(1,2,1)
plt.imshow(img,cmap="gray")
plt.subplot(1,2,2)
plt.imshow(img,cmap="gray")
plt.show()

#LOG

import cv2 
import matplotlib.pyplot as plt
import numpy as np

img = cv2.imread("ma grey.png",0)

c = 255 / np.log10(1 + np.max(img))

img_log = c * (np.log10(img + 1))
img_log = np.array(img_log, dtype = np.uint8)
plt.figure(figsize=(20, 20))
plt.subplot(1,2,1)
plt.imshow(img,cmap="gray")
plt.subplot(1,2,2)
plt.imshow(img,cmap="gray")
plt.show()

#Gamma x Sharpen

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img = cv.imread("magamma.png",1)
kernel = np.array([
                   [0, -1, 0],
                   [-1, 5, -1],
                   [0, -1, 0]
])

img_out = cv.filter2D(img, -1, kernel)
plt.figure(figsize=(20, 20))
plt.subplot(1,2,1)
plt.imshow(img,cmap="gray")
plt.subplot(1,2,2)
plt.imshow(img_out,cmap="gray")
plt.show()

#log x sharpen 
#Gamma x Sharpen

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img = cv.imread("malog.png",1)
kernel = np.array([
                   [0, -1, 0],
                   [-1, 5, -1],
                   [0, -1, 0]
])

img_out = cv.filter2D(img, -1, kernel)
plt.figure(figsize=(20, 20))
plt.subplot(1,2,1)
plt.imshow(img,cmap="gray")
plt.subplot(1,2,2)
plt.imshow(img_out,cmap="gray")
plt.show()